# Generated by Django 5.1.3 on 2025-06-16 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningcourses',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='courses/images', verbose_name='تصویر دوره'),
        ),
        migrations.AddField(
            model_name='learningcourses',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='وضعیت دوره'),
        ),
        migrations.AddField(
            model_name='learningworkshops',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='courses/images', verbose_name='تصویر دوره'),
        ),
        migrations.AddField(
            model_name='learningworkshops',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='وضعیت دوره'),
        ),
    ]
